# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: southside
      MARIADB_DATABASE: southside
      MARIADB_PASSWORD: test123
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
    ports:
      - 3306:3306
